### ISSUE TITLE
 你好，example2里有个资源缺少了

### ISSUE THREAD

**Issue by curtis-go** [lhywell/map#1]
拜读了你的项目，看到https://github.com/lhywell/map/blob/master/example2/leaf%2B.html  里有资源缺少了，能补上吗

**Comment by lhywell** [comment]
你好：
案例中是加载的leaflet+mapbox，mapbox是外网的需要翻墙，并且注册的是我个人的access_token，如果用于商业开发请注册自己access_token

文章可以看我的文章 https://github.com/lhywell/map/blob/master/2.5README.md
相关注册请到这里：https://www.mapbox.com/studio/account/tokens/


--
李慧吟
2018年9月21日

在 2018-08-28 10:59:49，"jixianlqb" <notifications@github.com> 写道：


Closed #1.
